id: D8E43E0D0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-27T08:25:22+00:00'
last_modified: '2022-05-27T10:02:27.679651+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a4bd:
      image_group_id: I1PD95907
      title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1557
      order: 62
      base_file: a4bd.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
