id: PE17D4F44
initial_creation_type: ocr
source_metadata:
  volumes:
    78f3cfef30884cce95e0777a21c268d5:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དབུ་མའི་རྒྱན་གྱི་འགྲེལ་པ།
      total_pages: 1557
      volume_number: 62
